name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.CI_TOKEN }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: |
        make install
    - name: Format
      run: |
        make format
    - name: commit
      uses: EndBug/add-and-commit@v9
      with:
        message: Auto formatted by ${{ github.workflow }} workflow
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
    - uses: codecov/codecov-action@v2
