name: Mutate

on:
  pull_request:
    branches: [ master ]

jobs:
  mutate:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          
      - name: fetch
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          
      - name: Install dependencies
        run: |
          make install
          
      - name: Run radiation
        id: mutate
        run: |
          NL=$'\n'
          OUTPUT="# Radiation mutations report"
          OUTPUT="${OUTPUT}${NL}$(poetry run radiation --line-limit 2 --diff-command='git diff origin/master' run)"
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-output name=OUTPUT::$OUTPUT"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: ${{ steps.mutate.outputs.OUTPUT }}
          comment_includes: '# Radiation mutations report'
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
