name: Mutate

on:
  pull_request:
    branches: [ master ]

jobs:
  mutate:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install
        run: poetry install

      - name: mutate
        id: mutate
        run: |
          OUTPUT=$(poetry run radiation run")
          echo "::set-output name=OUTPUT::$OUTPUT"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: ${{ steps.mutate.outputs.OUTPUT }}
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
